// Code generated by codeembed. DO NOT EDIT.

package dccontracts

import (
	_ "embed"
)

// ByteCodeSha256: 392a5d3bb9f791025d580ac86fe39267241419e23e9c2beb1cab57f87570239e
// HexByteCodeSha256: db64ad788707480bfa98ddae12d9f2a008ca86ded7be942dcd549e217fb459f6
//go:embed hex/1001_validatorset_detroit.hex
var DCValidatorSetContractDetroitByteCode []byte
