// Code generated by codeembed. DO NOT EDIT.

package dccontracts

import (
	_ "embed"
)

// ByteCodeSha256: 6e3a18857e791fca9e3d8334ecc4a048eb4d6e2990e5bf97d89cbe042b9b51d9
// BinaryByteCodeSha256: fd4b22266fe26b81dfc4fb0064d6189c8531cbfeaae86d246b330b3498ef7918
//go:embed hex/1002_bridge_portland.hex
var DCBridgeContractPortlandByteCode []byte
