// Code generated by codeembed. DO NOT EDIT.

package dccontracts

import (
	_ "embed"
)

// ByteCodeSha256: 8d06029d8e6df0ac6d395d6f2eee6401bf6e5436daa8cf4afe6438843ab1aaa0
// BinaryByteCodeSha256: 3a58020b71be6ca88afaea5af0eb4bf556ce5f1a666c50c629d288e66dca6ffb
//go:embed hex/1002_bridge_detroit.hex
var DCBridgeContractDetroitByteCode []byte
